//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDGrabSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDGrabSharp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string btnBrowseCache {
            get {
                return ResourceManager.GetString("btnBrowseCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Grid.
        /// </summary>
        internal static string btnCustomGrid {
            get {
                return ResourceManager.GetString("btnCustomGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDeleteLineup {
            get {
                return ResourceManager.GetString("btnDeleteLineup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        internal static string btnHeadendCacheClear {
            get {
                return ResourceManager.GetString("btnHeadendCacheClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headends.
        /// </summary>
        internal static string btnHeadends {
            get {
                return ResourceManager.GetString("btnHeadends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnLineupAdd {
            get {
                return ResourceManager.GetString("btnLineupAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        internal static string btnLocationCacheClear {
            get {
                return ResourceManager.GetString("btnLocationCacheClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string btnSaveAs {
            get {
                return ResourceManager.GetString("btnSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        internal static string btnStationCacheClear {
            get {
                return ResourceManager.GetString("btnStationCacheClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string chAddedID {
            get {
                return ResourceManager.GetString("chAddedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string chAddedName {
            get {
                return ResourceManager.GetString("chAddedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string chAvailID {
            get {
                return ResourceManager.GetString("chAvailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string chAvailName {
            get {
                return ResourceManager.GetString("chAvailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Ask.
        /// </summary>
        internal static string checkAlwaysAsk {
            get {
                return ResourceManager.GetString("checkAlwaysAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineup.
        /// </summary>
        internal static string chLineup {
            get {
                return ResourceManager.GetString("chLineup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        internal static string chModified {
            get {
                return ResourceManager.GetString("chModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string chName {
            get {
                return ResourceManager.GetString("chName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string chStationID {
            get {
                return ResourceManager.GetString("chStationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Yesterday.
        /// </summary>
        internal static string ckIncludeYesterday {
            get {
                return ResourceManager.GetString("ckIncludeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Channel Number (Map).
        /// </summary>
        internal static string ckLogicalChannelNo {
            get {
                return ResourceManager.GetString("ckLogicalChannelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme MD5 (Required).
        /// </summary>
        internal static string ckMD5 {
            get {
                return ResourceManager.GetString("ckMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Cache.
        /// </summary>
        internal static string ckPersistentCache {
            get {
                return ResourceManager.GetString("ckPersistentCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme ID (Required).
        /// </summary>
        internal static string ckProgrammeID {
            get {
                return ResourceManager.GetString("ckProgrammeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Type (programme).
        /// </summary>
        internal static string ckShowType {
            get {
                return ResourceManager.GetString("ckShowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Affiliate (station).
        /// </summary>
        internal static string ckStationAfiliate {
            get {
                return ResourceManager.GetString("ckStationAfiliate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Callsign (station).
        /// </summary>
        internal static string ckStationCallsign {
            get {
                return ResourceManager.GetString("ckStationCallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station ID (station).
        /// </summary>
        internal static string ckStationID {
            get {
                return ResourceManager.GetString("ckStationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Name (station).
        /// </summary>
        internal static string ckStationName {
            get {
                return ResourceManager.GetString("ckStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration saved.
        /// </summary>
        internal static string ConfigSaved {
            get {
                return ResourceManager.GetString("ConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Name.
        /// </summary>
        internal static string CustomEntryCustomName {
            get {
                return ResourceManager.GetString("CustomEntryCustomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineup.
        /// </summary>
        internal static string CustomEntryLineup {
            get {
                return ResourceManager.GetString("CustomEntryLineup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CustomEntryName {
            get {
                return ResourceManager.GetString("CustomEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station ID.
        /// </summary>
        internal static string CustomEntryStationID {
            get {
                return ResourceManager.GetString("CustomEntryStationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Custom Channel names.
        /// </summary>
        internal static string CustomGridEntry {
            get {
                return ResourceManager.GetString("CustomGridEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDGrabSharp {0} (Alpha).
        /// </summary>
        internal static string frmMainTitle {
            get {
                return ResourceManager.GetString("frmMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string frmOptionsTitle {
            get {
                return ResourceManager.GetString("frmOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Lineups.
        /// </summary>
        internal static string gbAccountLineups {
            get {
                return ResourceManager.GetString("gbAccountLineups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Lineups {0} of {1}.
        /// </summary>
        internal static string gbAccountLineupsNormal {
            get {
                return ResourceManager.GetString("gbAccountLineupsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Lineups {0} of {1} changes remaining {2}.
        /// </summary>
        internal static string gbAccountLineupsRemaining {
            get {
                return ResourceManager.GetString("gbAccountLineupsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Channels.
        /// </summary>
        internal static string gbAddedChannels {
            get {
                return ResourceManager.GetString("gbAddedChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Channels.
        /// </summary>
        internal static string gbAvailableChannels {
            get {
                return ResourceManager.GetString("gbAvailableChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLTV Channel ID Map.
        /// </summary>
        internal static string gbChannelIDMap {
            get {
                return ResourceManager.GetString("gbChannelIDMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string gbCreds {
            get {
                return ResourceManager.GetString("gbCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Channel Entry.
        /// </summary>
        internal static string gbCustomEntry {
            get {
                return ResourceManager.GetString("gbCustomEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headend/Lineup.
        /// </summary>
        internal static string gbHeadends {
            get {
                return ResourceManager.GetString("gbHeadends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Cache.
        /// </summary>
        internal static string gbPersistentCache {
            get {
                return ResourceManager.GetString("gbPersistentCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme Retrieval Options.
        /// </summary>
        internal static string gbRetrievalOptions {
            get {
                return ResourceManager.GetString("gbRetrievalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station mapping.
        /// </summary>
        internal static string gbStationMap {
            get {
                return ResourceManager.GetString("gbStationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        internal static string gbStations {
            get {
                return ResourceManager.GetString("gbStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules Direct XMLTV Attributes.
        /// </summary>
        internal static string gbXmlTVAttr {
            get {
                return ResourceManager.GetString("gbXmlTVAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Selection.
        /// </summary>
        internal static string grpLocation {
            get {
                return ResourceManager.GetString("grpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Filename.
        /// </summary>
        internal static string lbCacheFilename {
            get {
                return ResourceManager.GetString("lbCacheFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example include date range {0} - {1}.
        /// </summary>
        internal static string lbDateRangeInfo {
            get {
                return ResourceManager.GetString("lbDateRangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel display-name source.
        /// </summary>
        internal static string lblChannelDisplayName {
            get {
                return ResourceManager.GetString("lblChannelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineup.
        /// </summary>
        internal static string lblLineup {
            get {
                return ResourceManager.GetString("lblLineup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lbLogin {
            get {
                return ResourceManager.GetString("lbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programme Items/Request.
        /// </summary>
        internal static string lblProgrammeItems {
            get {
                return ResourceManager.GetString("lblProgrammeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Items/Request.
        /// </summary>
        internal static string lblScheduleItems {
            get {
                return ResourceManager.GetString("lblScheduleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string lbPostCode {
            get {
                return ResourceManager.GetString("lbPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval Period (Days).
        /// </summary>
        internal static string lbProgrammePeriod {
            get {
                return ResourceManager.GetString("lbProgrammePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string OptionsbtnCancel {
            get {
                return ResourceManager.GetString("OptionsbtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OptionsbtnOK {
            get {
                return ResourceManager.GetString("OptionsbtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate.
        /// </summary>
        internal static string rdAffiliate {
            get {
                return ResourceManager.GetString("rdAffiliate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callsign.
        /// </summary>
        internal static string rdCallsign {
            get {
                return ResourceManager.GetString("rdCallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string rdCustom {
            get {
                return ResourceManager.GetString("rdCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string rdName {
            get {
                return ResourceManager.GetString("rdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station ID.
        /// </summary>
        internal static string rdStation {
            get {
                return ResourceManager.GetString("rdStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose save location for persistent cache.
        /// </summary>
        internal static string SaveCacheDialogCaption {
            get {
                return ResourceManager.GetString("SaveCacheDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select save location for configuration.
        /// </summary>
        internal static string SaveConfigDialogCaption {
            get {
                return ResourceManager.GetString("SaveConfigDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string toolStripMenuItemAbout {
            get {
                return ResourceManager.GetString("toolStripMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string toolStripMenuItemExit {
            get {
                return ResourceManager.GetString("toolStripMenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string toolStripMenuItemFile {
            get {
                return ResourceManager.GetString("toolStripMenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string toolStripMenuItemHelp {
            get {
                return ResourceManager.GetString("toolStripMenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string toolStripMenuItemOptions {
            get {
                return ResourceManager.GetString("toolStripMenuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string toolStripMenuItemRun {
            get {
                return ResourceManager.GetString("toolStripMenuItemRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string toolStripMenuItemTools {
            get {
                return ResourceManager.GetString("toolStripMenuItemTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string tpGeneral1 {
            get {
                return ResourceManager.GetString("tpGeneral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules Direct.
        /// </summary>
        internal static string tpSD1Title {
            get {
                return ResourceManager.GetString("tpSD1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLTV Mapping.
        /// </summary>
        internal static string tpXMLTV1 {
            get {
                return ResourceManager.GetString("tpXMLTV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string tsStatusDefaultText {
            get {
                return ResourceManager.GetString("tsStatusDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml).
        /// </summary>
        internal static string XmlFiles {
            get {
                return ResourceManager.GetString("XmlFiles", resourceCulture);
            }
        }
    }
}
